spring.application.name=odontologica
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:~/clinicaOdontologicaTest
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.file.name=resultado.log
logging.level.root=INFO
logging.level.com.clinica.odontologica=DEBUG
logging.pattern.console=[%d{yyyy-MM-dd HH:mm:ss}] [ %-5p] [%logger{0}:%L] %m%n
logging.pattern.file=[%d{yyyy-MM-dd HH:mm:ss}] [ %-5p] [%logger{0}:%L] %m%n
